# Generated by mnemonica-stubgen. Do not edit.
from typing import Any

from app import User

class Sub(User):
    tag: str
    def __init__(self, tag: str) -> None: ...

def sub_handler(self: Any, tag: str) -> None: ...
