# Generated by mnemonica-stubgen. Do not edit.
from typing import Any

from somewhere import External

class Ext(External):
    tag: str
    def __init__(self, tag: str) -> None: ...

def ext_handler(self: Any, tag: str) -> None: ...
