# Generated by mnemonica-stubgen. Do not edit.
from typing import Any, Awaitable, Generator, Protocol

class Admin(User):
    role: str
    def __init__(self, role: str) -> None: ...
    @classmethod
    def of(cls, parent: User, role: str) -> Admin: ...

class AsyncUser:
    name: str
    def __init__(self, name: str) -> None: ...
    def __await__(self) -> Generator[Any, None, AsyncUser]: ...

class User:
    name: str
    Admin: _User_Admin
    def __init__(self, name: str) -> None: ...

class _User_Admin(Protocol):
    def __call__(self, role: str) -> Admin: ...
