"""mnemonica-stubgen: the Python analogue of tactica (P5).

Reads a user package with the stdlib `ast` module (never importing user
code), finds mnemonica types in all three definition forms, and writes
`.pyi` stubs that declare each subtype as a typed attribute of its parent
class — so `user.Admin(...)` is fully typed for mypy AND pyright strict.

Forms recognized:
- A: `@Parent.define` on a bare class (the decorator names the parent);
  a root when the decorator is `@define` / `@collection.define`.
- B: `@Parent.define` on `class Admin(User)` — same detection, the base
  is verified against the decorator.
- C: `Admin = Parent.define("Admin", handler)` — the assignment form;
  `User = define("User", handler)` declares a root.

Emitted stub shape (probed against both checkers before building):
every mnemonica type becomes a PLAIN class (decorators stripped, so
checkers see the real hierarchy) — the runtime `Mnemonic` base and its
metaclass are intentionally NOT redeclared: pyright (like the runtime)
resolves constructor calls through the metaclass `__call__`, which is
typed `Any` (async construction returns the AsyncChain awaitable), and
the result would be vacuously untyped. Plain classes keep constructor
arguments fully checked. The base is dropped only for roots; subtypes
keep their parent, so attribute inheritance still types. Each parent
gains one tiny Protocol per subtype, `Admin: _User_Admin`, whose
`__call__` carries the handler's argument types and returns the subtype
— `Awaitable[Sub]` for async handlers, so `await user.Admin(...)` types
as `Admin`. Async types also get a checker-facing `def __init__` plus
`__await__`, so awaiting an async ROOT construction (`await User(...)`)
types correctly and matches the runtime (the construction returns the
AsyncChain awaitable, which has `__await__`). Subtypes also get `of()`
— the always-typed construction path — declared explicitly, since the
metaclass classmethod is not visible on plain stub classes.

Instance attributes are collected from `self.x = ...` assignments in
the constructor (`self.x = param` picks up the parameter's annotation);
anything unrecognized is `Any`.

Limitations (recorded in docs/conformance.md): subtypes are keyed by
type name across the package (names must be unique); a subtype whose
parent lives in another module of the package is not linked (the parent
attribute is skipped with a warning); modules without mnemonica types
get no stub.

Usage: `python -m mnemonica.stubgen <package-dir> [--out <dir>]`
Output is deterministic (everything sorted) and idempotent.
"""

import argparse
import ast
import sys
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

_HEADER = "# Generated by mnemonica-stubgen. Do not edit.\n"

_DEF_ANY = "Any"


@dataclass
class _Type:
    """One mnemonica type (or plain class) found in a module."""

    name: str
    module: str
    parent: str | None = None
    bases: list[str] = field(default_factory=list[str])
    init_params: list[str] = field(default_factory=list[str])
    is_async: bool = False
    attrs: list[tuple[str, str]] = field(default_factory=list[tuple[str, str]])
    methods: list[str] = field(default_factory=list[str])
    alias: str | None = None
    is_plain: bool = False  # not a mnemonica type: keep as written


@dataclass
class _Module:
    """Parse result for one module of the package."""

    name: str  # dotted, relative to the package root
    imports: list[str] = field(default_factory=list[str])
    types: list[_Type] = field(default_factory=list[_Type])
    functions: list[str] = field(default_factory=list[str])


def _unparse(node: ast.AST | None) -> str | None:
    """ast.unparse with a None pass-through (annotations may be absent)."""
    if node is None:
        return None
    return ast.unparse(node)


def _params(args: ast.arguments, skip_first: bool) -> list[str]:
    """Render an ast.arguments to stub parameter strings."""
    parts: list[str] = []
    positional = list(args.posonlyargs) + list(args.args)
    if skip_first and positional:
        positional = positional[1:]
    default_offset = len(positional) - len(args.defaults)
    for index, param in enumerate(positional):
        ann = _unparse(param.annotation) or _DEF_ANY
        rendered = f"{param.arg}: {ann}"
        if index >= default_offset:
            rendered = f"{rendered} = ..."
        parts.append(rendered)
    if args.vararg is not None:
        ann = _unparse(args.vararg.annotation) or _DEF_ANY
        parts.append(f"*{args.vararg.arg}: {ann}")
    elif args.kwonlyargs:
        parts.append("*")
    for param, default in zip(args.kwonlyargs, args.kw_defaults, strict=True):
        ann = _unparse(param.annotation) or _DEF_ANY
        rendered = f"{param.arg}: {ann}"
        if default is not None:
            rendered = f"{rendered} = ..."
        parts.append(rendered)
    if args.kwarg is not None:
        ann = _unparse(args.kwarg.annotation) or _DEF_ANY
        parts.append(f"**{args.kwarg.arg}: {ann}")
    result = parts
    return result


def _self_attrs(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> list[tuple[str, str]]:
    """Instance attributes assigned in the constructor body, sorted.

    `self.x = param` picks up the parameter's annotation; anything else
    is Any.
    """
    param_anns = {
        param.arg: (_unparse(param.annotation) or _DEF_ANY)
        for param in [*fn.args.posonlyargs, *fn.args.args, *fn.args.kwonlyargs]
    }
    found: dict[str, str] = {}
    for node in ast.walk(fn):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if (
                    isinstance(target, ast.Attribute)
                    and isinstance(target.value, ast.Name)
                    and target.value.id == "self"
                ):
                    ann = _DEF_ANY
                    if isinstance(node.value, ast.Name):
                        ann = param_anns.get(node.value.id, _DEF_ANY)
                    found.setdefault(target.attr, ann)
        elif isinstance(node, ast.AnnAssign) and (
            isinstance(node.target, ast.Attribute)
            and isinstance(node.target.value, ast.Name)
            and node.target.value.id == "self"
        ):
            found.setdefault(node.target.attr, _unparse(node.annotation) or _DEF_ANY)
    result = sorted(found.items())
    return result


def _method_lines(node: ast.ClassDef, exclude: "set[str] | None" = None) -> list[str]:
    """Stub lines for the methods of a class (constructors excludable —
    mnemonica types re-emit their constructor from the detected handler)."""
    excluded: set[str] = exclude if exclude is not None else set()
    lines: list[str] = []
    for item in node.body:
        if not isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if item.name in excluded:
            continue
        decorators = [ast.unparse(d) for d in item.decorator_list]
        prefix = "".join(f"@{d}\n    " for d in decorators)
        returns = _unparse(item.returns) or _DEF_ANY
        if item.name == "__init__":
            returns = "None"
        keyword = "async def" if isinstance(item, ast.AsyncFunctionDef) else "def"
        # staticmethods are not bound: no self to skip or re-add
        skip_first = "staticmethod" not in decorators
        method_params = _params(item.args, skip_first=skip_first)
        if skip_first:
            self_params = (
                "self" if not method_params else f"self, {', '.join(method_params)}"
            )
        else:
            self_params = ", ".join(method_params)
        rendered = f"    {prefix}{keyword} {item.name}({self_params}) -> {returns}: ..."
        lines.append(rendered)
    result = lines
    return result


def _constructor(node: ast.ClassDef) -> ast.FunctionDef | ast.AsyncFunctionDef | None:
    """The constructor of a class-form type: __ainit__ wins over __init__."""
    own_init: ast.FunctionDef | ast.AsyncFunctionDef | None = None
    own_ainit: ast.FunctionDef | ast.AsyncFunctionDef | None = None
    for item in node.body:
        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if item.name == "__init__":
                own_init = item
            elif item.name == "__ainit__":
                own_ainit = item
    result = own_ainit if own_ainit is not None else own_init
    return result


def _define_parent(decorator: ast.expr, class_names: set[str]) -> str | None:
    """The parent type named by a define decorator, or None for a root.

    `@define` / `@collection.define` / anything not naming an in-module
    class is a root; `@User.define` names the parent.
    """
    if isinstance(decorator, ast.Name):
        result = "root" if decorator.id == "define" else None
        return result
    if isinstance(decorator, ast.Attribute) and decorator.attr == "define":
        if isinstance(decorator.value, ast.Name) and decorator.value.id in class_names:
            result = decorator.value.id
            return result
        result = "root"
        return result
    result = None
    return result


def _handler_from_call(call: ast.Call) -> ast.expr | None:
    """The handler argument of a define(...) call, when present."""
    if len(call.args) < 2:
        return None
    result = call.args[1]
    return result


def _type_from_assignment(
    node: ast.Assign,
    module: str,
    functions: dict[str, ast.FunctionDef | ast.AsyncFunctionDef],
    class_names: set[str],
) -> _Type | None:
    """Form C: `Admin = User.define("Admin", handler)` / `define(...)`."""
    if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
        return None
    call = node.value
    if not isinstance(call, ast.Call):
        return None
    parent: str | None = None
    if isinstance(call.func, ast.Name) and call.func.id == "define":
        parent = None
    elif (
        isinstance(call.func, ast.Attribute)
        and call.func.attr == "define"
        and isinstance(call.func.value, ast.Name)
    ):
        value = call.func.value.id
        if value in class_names:
            parent = value
        elif value == "collection":
            parent = None  # `collection.define(...)` declares a root
        else:
            parent = value  # a parent outside the package
    else:
        return None
    if not call.args or not isinstance(call.args[0], ast.Constant):
        return None
    type_name = call.args[0].value
    if not isinstance(type_name, str):
        return None
    var_name = node.targets[0].id
    handler = _handler_from_call(call)
    init_params: list[str] = []
    is_async = False
    attrs: list[tuple[str, str]] = []
    if isinstance(handler, ast.Name):
        fn = functions.get(handler.id)
        if isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
            init_params = _params(fn.args, skip_first=True)
            is_async = isinstance(fn, ast.AsyncFunctionDef)
            attrs = _self_attrs(fn)
    elif isinstance(handler, ast.Lambda):
        # handler lambdas conventionally take self like def handlers
        init_params = _params(handler.args, skip_first=True)
    result = _Type(
        name=type_name,
        module=module,
        parent=parent,
        init_params=init_params,
        is_async=is_async,
        attrs=attrs,
        alias=var_name if var_name != type_name else None,
    )
    return result


def _parse_module(path: Path, module_name: str) -> _Module:
    """Parse one module: imports, classes, functions, form-C assignments."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    imports: list[str] = []
    functions: dict[str, ast.FunctionDef | ast.AsyncFunctionDef] = {}
    function_lines: list[str] = []
    types: list[_Type] = []
    class_names = {node.name for node in tree.body if isinstance(node, ast.ClassDef)}
    for node in tree.body:
        if isinstance(node, ast.Import):
            names = [alias.name for alias in node.names]
            if all(not name.startswith("mnemonica") for name in names):
                imports.append(ast.unparse(node))
        elif isinstance(node, ast.ImportFrom):
            # stub classes are plain (no Mnemonic base, no metaclass):
            # nothing from mnemonica is needed in the emitted stub
            if node.module is None or not node.module.startswith("mnemonica"):
                imports.append(ast.unparse(node))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions[node.name] = node
            returns = _unparse(node.returns) or _DEF_ANY
            keyword = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
            rendered = (
                f"{keyword} {node.name}("
                f"{', '.join(_params(node.args, skip_first=False))}"
                f") -> {returns}: ..."
            )
            function_lines.append(rendered)
        elif isinstance(node, ast.ClassDef):
            parent: str | None = None
            is_root = False
            for decorator in node.decorator_list:
                found = _define_parent(decorator, class_names)
                if found is not None:
                    is_root = found == "root"
                    parent = None if is_root else found
                    break
            constructor = _constructor(node)
            if parent is not None or is_root:
                init_params: list[str] = []
                is_async = False
                attrs: list[tuple[str, str]] = []
                if constructor is not None:
                    init_params = _params(constructor.args, skip_first=True)
                    is_async = isinstance(constructor, ast.AsyncFunctionDef)
                    attrs = _self_attrs(constructor)
                types.append(
                    _Type(
                        name=node.name,
                        module=module_name,
                        parent=parent,
                        init_params=init_params,
                        is_async=is_async,
                        attrs=attrs,
                        methods=_method_lines(node, exclude={"__init__", "__ainit__"}),
                    )
                )
            else:
                types.append(
                    _Type(
                        name=node.name,
                        module=module_name,
                        bases=[ast.unparse(b) for b in node.bases],
                        methods=_method_lines(node),
                        is_plain=True,
                    )
                )
        elif isinstance(node, ast.Assign):
            assigned = _type_from_assignment(node, module_name, functions, class_names)
            if assigned is not None:
                types.append(assigned)
    result = _Module(
        name=module_name,
        imports=sorted(set(imports)),
        types=types,
        functions=sorted(function_lines),
    )
    return result


def _class_line(type_info: _Type, registry: dict[str, _Type]) -> str:
    """The `class Name(bases...):` line for a type.

    Plain-class stubs on purpose: the runtime metaclass __call__ is typed
    Any (async returns the awaitable), so redeclaring it would make every
    constructor call vacuously untyped. Roots get no base at all.
    """
    if type_info.is_plain:
        bases = type_info.bases
    elif type_info.parent is None:
        bases = []
    else:
        # the parent names stays the base — including when it lives
        # outside the package (kept as written; no attribute is linked)
        bases = [type_info.parent]
    rendered_bases = f"({', '.join(bases)})" if bases else ""
    result = f"class {type_info.name}{rendered_bases}:"
    return result


def _emit_module(module: _Module, registry: dict[str, _Type]) -> str:
    """Render the .pyi source for one module."""
    local_names = {t.name for t in module.types}
    # subtypes attributed to parents declared in this module, by parent;
    # a subtype declared in another module of the package is not linked
    # (the Protocol would reference a name this module does not import)
    children: dict[str, list[_Type]] = {}
    for type_info in registry.values():
        if (
            type_info.parent is not None
            and type_info.parent in local_names
            and type_info.module == module.name
        ):
            children.setdefault(type_info.parent, []).append(type_info)
    for group in children.values():
        group.sort(key=lambda t: t.name)
    has_async = any(t.is_async for t in module.types if not t.is_plain)
    typing_imports = ["Any"]
    if has_async:
        typing_imports.extend(["Awaitable", "Generator"])
    if children:
        typing_imports.append("Protocol")
    lines: list[str] = [
        _HEADER.rstrip("\n"),
        f"from typing import {', '.join(typing_imports)}",
        "",
    ]
    if module.imports:
        lines.extend(module.imports)
        lines.append("")
    for type_info in sorted(module.types, key=lambda t: t.name):
        lines.append(_class_line(type_info, registry))
        body: list[str] = []
        for attr, ann in type_info.attrs:
            body.append(f"    {attr}: {ann}")
        for child in children.get(type_info.name, []):
            body.append(f"    {child.name}: _{type_info.name}_{child.name}")
        self_params = (
            "self"
            if not type_info.init_params
            else f"self, {', '.join(type_info.init_params)}"
        )
        if type_info.is_async and not type_info.is_plain:
            body.append(f"    def __init__({self_params}) -> None: ...")
            body.append(
                "    def __await__(self)"
                f" -> Generator[Any, None, {type_info.name}]: ..."
            )
        elif type_info.init_params:
            body.append(f"    def __init__({self_params}) -> None: ...")
        # the always-typed construction path, declared explicitly (the
        # runtime classmethod lives on the metaclass, not visible here);
        # one level deep only — a subtype of a subtype inherits a
        # same-named classmethod whose parameter list differs, and mypy
        # would reject the override; deeper levels construct through the
        # parent's attribute, which is fully typed
        parent_type = next(
            (t for t in module.types if t.name == type_info.parent), None
        )
        if (
            not type_info.is_plain
            and parent_type is not None
            and parent_type.parent is None
        ):
            parent = type_info.parent
            assert parent is not None
            of_params = (
                f"cls, parent: {parent}"
                if not type_info.init_params
                else f"cls, parent: {parent}, {', '.join(type_info.init_params)}"
            )
            if type_info.is_async:
                of_returns = f"Awaitable[{type_info.name}]"
            else:
                of_returns = type_info.name
            body.append(
                f"    @classmethod\n    def of({of_params}) -> {of_returns}: ..."
            )
        body.extend(type_info.methods)
        if body:
            lines.extend(body)
        else:
            lines.append("    ...")
        if type_info.alias is not None:
            lines.append("")
            lines.append(f"{type_info.alias} = {type_info.name}")
        lines.append("")
    for type_info in sorted(module.types, key=lambda t: t.name):
        for child in children.get(type_info.name, []):
            lines.append(f"class _{type_info.name}_{child.name}(Protocol):")
            if child.is_async:
                returns = f"Awaitable[{child.name}]"
            else:
                returns = child.name
            call_params = (
                "self"
                if not child.init_params
                else f"self, {', '.join(child.init_params)}"
            )
            lines.append(f"    def __call__({call_params}) -> {returns}: ...")
            lines.append("")
    lines.extend(module.functions)
    result = "\n".join(lines).rstrip("\n") + "\n"
    return result


def _module_name_for(path: Path, root: Path) -> str:
    """Dotted module name of a file relative to the package root."""
    relative = path.relative_to(root).with_suffix("")
    parts = list(relative.parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    result = ".".join(parts)
    return result


def generate(package_dir: Path, out_dir: Path | None = None) -> list[Path]:
    """Generate .pyi stubs for every module with mnemonica types.

    Returns the written files (sorted). Deterministic and idempotent.
    """
    root = package_dir.resolve()
    target = root if out_dir is None else out_dir.resolve()
    modules: list[_Module] = []
    for path in sorted(root.rglob("*.py")):
        modules.append(_parse_module(path, _module_name_for(path, root)))
    registry: dict[str, _Type] = {}
    for module in modules:
        for type_info in module.types:
            if not type_info.is_plain:
                registry[type_info.name] = type_info
    for type_info in registry.values():
        if (
            type_info.parent is not None
            and type_info.parent in registry
            and type_info.module != registry[type_info.parent].module
        ):
            print(
                f"mnemonica-stubgen: warning: {type_info.name} extends"
                f" {type_info.parent} from another module"
                f" ({registry[type_info.parent].module}); the parent"
                " attribute is not linked",
                file=sys.stderr,
            )
    written: list[Path] = []
    for module in modules:
        typed = [t for t in module.types if not t.is_plain]
        if not typed:
            continue
        rel = (
            Path(*module.name.split(".")).with_suffix(".pyi")
            if module.name
            else Path("__init__.pyi")
        )
        destination = target / rel
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(_emit_module(module, registry), encoding="utf-8")
        written.append(destination)
    result = sorted(written)
    return result


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry: python -m mnemonica.stubgen <package-dir> [--out <dir>]."""
    parser = argparse.ArgumentParser(
        prog="mnemonica-stubgen",
        description="Generate .pyi stubs that type mnemonica subtype attributes.",
    )
    parser.add_argument("package_dir", type=Path, help="the user package directory")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="where to write the stubs (default: next to the sources)",
    )
    arguments = parser.parse_args(argv)
    written = generate(arguments.package_dir, arguments.out)
    for destination in written:
        print(destination)
    result = 0
    return result


if __name__ == "__main__":
    sys.exit(main())
